### ISSUE TITLE
[BUG]: Talking Head frame skin broken

### ISSUE THREAD

**Issue by TreizeEU** [jncl/Skinner#119]
Skinning of Retail's "Talking head" frame is a bit broken.

![WoWScrnShot_081324_091456](https://github.com/user-attachments/assets/741212c9-e043-4b21-af01-c46c3a321801)

**Comment by jncl** [comment]
Hi, 
    I'm not seeing what you posted as a screenshot, the TalkingHead frame is skinned properly for me.
    Are there any error message that you're getting when this happens?
    Are you running any other AddOn(s) that may change the TalkingHead frame in some way?

**Comment by TreizeEU** [comment]
Hi Jncl.

It was intended as a cropped screenshot around where the Talking Head frame normally is. I don't use any other addons to move it or resize it. The text is hard to see, and the background skin seems to repeat itself over and over instead of being from border to border.

But here's the full-size screenshot:

![WoWScrnShot_081324_091456](https://github.com/user-attachments/assets/e1dbe12c-cd8f-430c-9d90-7d205d937faf)
