### ISSUE TITLE
Can't see items in my Mage (only) Character Screen 

### ISSUE THREAD

**Issue by Galthariel** [jncl/Skinner#12]
**WoW Version**
Retail

**AddOn skin name**
Not Applicable

**Describe the bug**
Can't see my mage Item in the Character Screen. I can though in my other two characters as usual. There are no lua errors to share but disabling Character Frames under Player Frames fixes the issue

![2023-06-26_16-17-45](https://github.com/jncl/Skinner/assets/51491805/6c67f31a-ff99-43f4-8356-300b55b8656b)

**Comment by jncl** [comment]
What AddOns are you using to enhance the CharacterFrame?

**Comment by Galthariel** [comment]
The only ones are Kibs Item Level and DejaCharacterStats. I already tried to disable both and the issue persists. Another problem I just noticed in the Professions UI Frame is that with Skinner enabled I can't use the Blizz Experiment option. Clicking on any button to test the mats doesn't open the option to pick the mat I want. Again, disabling Profession under Skinner Player Frames fixes the issue.

**Comment by Galthariel** [comment]
Here is the error for the Professions UI

19x Skinner/RetailSupport/PlayerFrames_Retail.lua:4142: attempt to call field 'ToggleProfessionsItemFlyout' (a nil value)
[string "@Skinner/RetailSupport/PlayerFrames_Retail.lua"]:4142: in function <Skinner/RetailSupport/PlayerFrames_Retail.lua:4141>
[string "=(tail call)"]: ?
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeFlyoutInstance.lua"]:25: in function `ToggleProfessionsItemFlyout'
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua"]:966: in function <...emplates/Blizzard_ProfessionsRecipeSchematicForm.lua:959>

Locals:
owner = Button {
 0 = <userdata>
 SetItemButtonTexture = <function> defined @FrameXML/ItemButtonTemplate.lua:674
 SetItem = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:3
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 showMatchHighlight = true
 locked = false
 CropFrame = Texture {
 }
 icon = ProfessionsFrameIconTexture {
 }
 GetBagID = <function> defined @FrameXML/ItemButtonTemplate.lua:643
 count = 0
 UpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:91
 UpdateCraftedProfessionsQualityShown = <function> defined @FrameXML/ItemButtonTemplate.lua:461
 SetCurrency = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:8
 PostOnShow = <function> defined @FrameXML/ItemButtonTemplate.lua:414
 GetItemContextOverlayMode = <function> defined @FrameXML/ItemButtonTemplate.lua:471
 SetItemSource = <function> defined @FrameXML/ItemButtonTemplate.lua:528
 IsModifyingRequired = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:51
 ColorOverlay = Texture {
 }
 UpdateCursor = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:65
 GetCurrencyID = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:20
 SetBagID = <function> defined @FrameXML/ItemButtonTemplate.lua:639
 UpdateItemContextOverlay = <function> defined @FrameXML/ItemButtonTemplate.lua:488
 SetCropOverlayShown = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:43
 Count = FontString {
 }
 SetItemButtonAnchorPoint = <function> defined @FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = ProfessionsFrameSearchOverlay {
 }
 NormalTexture = ProfessionsFrameNormalTexture {
 }
 IconOverlay2 = Texture {
 }
 OnUpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:651
 OnItemContextChanged = <function> defined @FrameXML/ItemButtonTemplate.lua:410
 isModifyingRequired = false
 SetModifyingRequired = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:47
 SetItemButtonScale = <function> defined @FrameXML/ItemButtonTemplate.lua:623
 isCraftedItem = false
 noProfessionQualityOverlay = false
 isProfessionItem = false
 HighlightTexture = Texture {
 }
 itemContextMatchResult = 3
 InputOverlay = Frame {
 }
 AddIcon = Texture {
 }
 UpdateOverlay = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:55
 QualityOverlay = Texture {
 }
 GetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:610
 SetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:532
 GetSlotAndBagID = <function> defined @FrameXML/ItemButtonTemplate.lua:647
 ItemContextOverlay = Texture {
 }
 Icon = Texture {
 }
 SetItemButtonTextureVertexColor = <function> defined @FrameXML/ItemButtonTemplate.lua:670
 GetItemID = <function> defined @FrameXML/ItemButtonTemplate.lua:591
 GetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:627
 RegisterBagButtonUpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:657
 SetItemButtonQuality = <function> defined @FrameXML/ItemButtonTemplate.lua:662
 PushedTexture = Texture {
 }
 SetLocked = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlot

**Comment by Galthariel** [comment]
SInce both issues it's in regard to buttons I think they can be related but...I'm not a dev so I may be wrong

**Comment by jncl** [comment]
Closing as there has been No additional response
