### ISSUE TITLE
[BUG]: Lua error Core/NPCFrames

### ISSUE THREAD

**Issue by HereticalHermit** [jncl/Skinner#125]
**WoW Version**
retail

**AddOn skin name**
NPCFrames

**Describe the bug**
22x Skinner/Core/UtilFuncs.lua:958: attempt to index local 'obj' (a nil value)
[string "@Skinner/Core/NPCFrames.lua"]:270: in function <Skinner/Core/NPCFrames.lua:184>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:370: in function <Skinner/Core/UtilFuncs.lua:363>
[string "=(tail call)"]: ?
[string "@Skinner/Core/AddonFrames.lua"]:131: in function `BlizzardFrames'
[string "@Skinner/Core/Skinner.lua"]:483: in function <Skinner/Core/Skinner.lua:483>

**Comment by MetalHeadSeven** [comment]
I'm getting a similar error.

2x Skinner/Core/UtilFuncs.lua:958: attempt to index local 'obj' (a nil value)
[string "@Skinner/Core/NPCFrames.lua"]:270: in function <Skinner/Core/NPCFrames.lua:184>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:370: in function <Skinner/Core/UtilFuncs.lua:363>
[string "=(tail call)"]: ?
[string "@Skinner/Core/Options.lua"]:723: in function <Skinner/Core/Options.lua:716>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:839: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:661>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ancedInterfaceOptions/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ns/libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

Locals:
self = <table> {
 blizzLoDFrames = <table> {
 }
 blizzFrames = <table> {
 }
 bColour = <table> {
 }
 mmButs = <table> {
 }
 db = <table> {
 }
 isTT = false
 Backdrop = <table> {
 }
 bdTexName = "Blizzard ChatFrame Background"
 isClscERAPTR = false
 iofDD = <table> {
 }
 bdbTexName = "Blizzard Tooltip"
 isRtl = true
 ttDelay = 0.200000
 ttHook = <table> {
 }
 isClsc = false
 name = "Skinner"
 ebRgns = <table> {
 }
 isClscERA = false
 L = <table> {
 }
 pbtt = <table> {
 }
 BTr = 1
 modUIBtns = <table> {
 }
 iofSkinnedPanels = <table> {
 }
 DBIcon = <table> {
 }
 bgTexName = "Blizzard Dialog Background Dark"
 BTb = 0
 itTex = "Interface\DialogFrame\UI-DialogBox-Background"
 lodAddons = <table> {
 }
 prdb = <table> {
 }
 backdrop = <table> {
 }
 ItemPimper = true
 ACD = <table> {
 }
 ttList = <table> {
 }
 tabFrames = <table> {
 }
 isClscBeta = false
 BTg = 0.501961
 HTg = 0.501961
 gmaxClr = <table> {
 }
 callbacks = <table> {
 }
 hooks = <table> {
 }
 optionsFrames = <table> {
 }
 isRtlPTR = false
 isRtlPTRX = false
 iofBtn = <table> {
 }
 LSM = <table> {
 }
 HTb = 0
 optTables = <table> {
 }
 uName = "Cayna"
 lmAddons = <table> {
 }
 modBtns = false
 isRtlBeta = false
 isPatch = true
 gradientCBar = <table> {
 }
 gradFrames = <table> {
 }
 initialized = <table> {
 }
 libsToSkin = <table> {
 }
 modules = <table> {
 }
 modChkBtns = false
 addonsToSkin = <table> {
 }
 tFDIDs = <table> {
 }
 oocTab = <table> {
 }
 ACR = <table> {
 }
 sbGlazed = <table> {
 }
 BT = <table> {
 }
 enabledState = true
 bbClr = <table> {
 }
 IT = <table> {
 }
 bbColour = <table> {
 }
 DT = <table> {
 }
 HTr = 1
 gradientTab = <table> {
 }
 tbClr = <table> {
 }
 bClr = <table> {
 }
 gminClr = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 sbClr = <table> {
 }
 sbTexture = "Interface\AddOns\Quartz\textures\Minimalist"
 HT = <table> {
 }
 modBtnBs = false
 gradientTex = "Interface\DialogFrame\UI-DialogBox-Background-Dark"
 optCheck = <table> {
 }
 orderedModules = <table> {
 }
 uCls = "PALADIN"
 baseName = "Skinner"
 otherAddons = <table> {
 }
 ignoreQT = <table> {
 }
 aboutPanels = <table> {
 }
 defaultModuleState = true
 skinTPLs = <table> {
 }
 isClscPTR = false
}
modelObj = QuestModelScene {
 ShadowOverlay = Texture {
 }
 Border = Texture {
 }
 normalIntensity = 0.750000
 ModelNameDivider = Texture {
 }
 tagToActor = <table> {
 }
 ModelBackground = Texture {
 }
 cameras = <table> {
 }
 ModelNameBackground = Texture {
 }
 TopBarBg = Texture {
 }
 actorTemplate = "ModelSceneActorTemplate"
 ModelTextFrame = Frame {
 }
 tagToCamera = <table> {
 }
 sf = Frame {
 }
 highlightIntensity = 1.200000
}
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 784
 MultiBarLeftActionButton10NormalTexture = MultiBarLeftActionButton10NormalTexture {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 422
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 MacroToolkitButton431 = MacroToolkitButton431 {
 }
 MultiBar7ActionButton5Icon = MultiBar7ActionButton5Icon {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 376
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_SHOW_ACTION_BAR5_T
