### ISSUE TITLE
[BUG]: LUA error with Frame:SetPropagateMouseClicks

### ISSUE THREAD

**Issue by HereticalHermit** [jncl/Skinner#128]
**WoW Version**
Retail

**AddOn skin name**
Skinner

**Describe the bug**
2x [ADDON_ACTION_BLOCKED] AddOn 'Skinner' tried to call the protected function 'Frame:SetPropagateMouseClicks()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPropagateMouseClicks'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:459: in function `UpdateMousePropagation'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:464: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:553: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:87: in function `OnAcquired'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:207: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:62: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:45: in function `OnEvent'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:106: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:105>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:109: in function `OnEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:143: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:142>

**Comment by jncl** [comment]
Hi,
This is caused by the WorldMap skin and seems to occur occasionally when the map is opened during combat.
Your options are either reload the UI, which usually fixes the issue for the session, or disable the skinning of the WorldMap frame completely.
