### ISSUE TITLE
 LFG Frame Lua Error

### ISSUE THREAD

**Issue by Galthariel** [jncl/Skinner#13]
**WoW Version**
Retail

**AddOn skin name**
Blizz LFG Frame

**Describe the bug**
2x ...aceSkinner/RetailSupport/UIFrames_Retail.lua:2248: attempt to index field 'Texture' (a nil value)
[string "@Skinner/RetailSupport/UIFrames_Retail.lua"]:2248: in function <...aceSkinner/RetailSupport/UIFrames_Retail.lua:2239>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/StaticPopup.lua"]:5428: in function `StaticPopupSpecial_Show'
[string "@FrameXML/LFGFrame.lua"]:231: in function <FrameXML/LFGFrame.lua:137>

Locals:
this = LFGDungeonReadyPopup {
 0 = <userdata>
 dungeonID = 2362
}
roleBtn = LFGDungeonReadyStatusGroupedHealer {
 0 = <userdata>
 statusIcon = LFGDungeonReadyStatusGroupedHealerStatusIcon {
 }
 count = LFGDungeonReadyStatusGroupedHealerCount {
 }
 texture = LFGDungeonReadyStatusGroupedHealerTexture {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "Healer"
 2 = "Tank"
 3 = "Damager"
}
(for control) = 1
_ = 1
type = "Healer"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Healer"
(*temporary) = "attempt to index field 'Texture' (a nil value)"
self = <table> {
 add2Table = <function> defined @Skinner/Core/SharedFuncs.lua:99
 makeIconSquare = <function> defined @Skinner/Core/UtilFuncs.lua:910
 ls_Toasts = <function> defined @Skinner/AddonSkins/ls_Toasts.lua:5
 checkShown = <function> defined @Skinner/Core/UtilFuncs.lua:431
 modules = <table> {
 }
 blizzFrames = <table> {
 }
 changeTandC = <function> defined @Skinner/Core/UtilFuncs.lua:244
 Debug3 = <function> defined @FrameXML/UIParent.lua:5261
 isButton = <function> defined @Skinner/Modules/UIButtons.lua:250
 bColour = <table> {
 }
 rarrow = "→"
 larrow = "←"
 setupOptions = <function> defined @Skinner/Core/SharedFuncs.lua:108
 ADDON_LOADED = <function> defined @Skinner/Core/AddonFrames.lua:182
 mmButs = <table> {
 }
 getInt = <function> defined @Skinner/Core/UtilFuncs.lua:653
 addButtonBorder = <function> defined @FrameXML/UIParent.lua:5261
 skinTooltip = <function> defined @Skinner/Core/MainFuncs.lua:1190
 db = <table> {
 }
 clrButtonFromBorder = <function> defined @FrameXML/UIParent.lua:5261
 SetupDefaults = <function> defined @Skinner/Core/Options.lua:6
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 isTT = false
 Backdrop = <table> {
 }
 bdTexName = "Blizzard ChatFrame Background"
 setActiveTab = <function> defined @Skinner/Core/UtilFuncs.lua:1218
 isClscERAPTR = false
 setupFramesOptions = <function> defined @Skinner/Core/UtilFuncs.lua:1290
 AddonFrames = <function> defined @Skinner/Core/AddonFrames.lua:111
 hasTextInName = <function> defined @Skinner/Core/UtilFuncs.lua:705
 iofDD = <table> {
 }
 bdbTexName = "KT - Border"
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 skinGlowBox = <function> defined @Skinner/Core/MainFuncs.lua:726
 isRtl = true
 XLoot = <function> defined @Skinner/AddonSkins/XLoot.lua:5
 hook = <function> defined @Skinner/Core/UtilFuncs.lua:757
 ttHook = <table> {
 }
 isClsc = false
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "Skinner"
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 round2 = <function> defined @Skinner/Core/UtilFuncs.lua:1168
 ebRgns = <table> {
 }
 findFrame2 = <function> defined @Skinner/Core/UtilFuncs.lua:529
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 addSkinFrame = <function> defined @Skinner/Core/MainFuncs.lua:332
 skinStatusBar = <function> defined @Skinner/Core/MainFuncs.lua:1027
 isClscERA = false
 clrBtnBdr = <function> defined @Skinner/Modules/UIButtons.lua:242
 L = <table> {
 }
 pbtt = <table> {
 }
 Debug = <function> defined @FrameXML/UIParent.lua:5261
 BTr = 0.780392
 checkLoadable = <function> defined @Skinner/Core/UtilFuncs.lua:417
 skinTabs = <function> defined @Skinner/Core/MainFuncs.lua:1153
 SetupOptions = <function> defined @Skinner/Core/Options.lua:93
 HTr = 0.800000
 modUI

**Comment by TreizeEU** [comment]
Hello Jncl.

I still seems to have issues with this, but I have a different lua error?

I'm on Skinner version beta10.50199.1.

Attaching a .zip with the lua error in a txt file and two screenshots.

[Skinner LFG role lua error.zip](https://github.com/jncl/Skinner/files/11928874/Skinner.LFG.role.lua.error.zip)

I'm not sure if one of them are related, or even an issue. The role-icons in the LFD/LFR frame isn't round like I think it was?
