### ISSUE TITLE
[BUG]:  Profession optional reagent flyout not working (again/still?)

### ISSUE THREAD

**Issue by TreizeEU** [jncl/Skinner#14]
**WoW Version**
Retail 10.1.0.50000
Skinner version beta10.50172.1

**Describe the bug**
I'm having a similar/identical issue as with ticket #11, but only since last update (to my knowledge) and with a different lua error.
It triggers every time I click the optional reagent for most things that I want to do, enchant onto a vellum or adding a spark to a ring craft, etc.

The lua error:

`19x Skinner/RetailSupport/PlayerFrames_Retail.lua:4142: attempt to call field 'ToggleProfessionsItemFlyout' (a nil value)
[string "@Skinner/RetailSupport/PlayerFrames_Retail.lua"]:4142: in function <Skinner/RetailSupport/PlayerFrames_Retail.lua:4141>
[string "=(tail call)"]: ?
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeFlyoutInstance.lua"]:25: in function `ToggleProfessionsItemFlyout'
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua"]:1213: in function <...emplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1211>

Locals:
owner = Button {
 0 = <userdata>
 SetItemButtonTexture = <function> defined @FrameXML/ItemButtonTemplate.lua:674
 SetItem = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:3
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 showMatchHighlight = true
 locked = false
 CropFrame = Texture {
 }
 icon = ProfessionsFrameIconTexture {
 }
 GetBagID = <function> defined @FrameXML/ItemButtonTemplate.lua:643
 count = 0
 UpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:91
 UpdateCraftedProfessionsQualityShown = <function> defined @FrameXML/ItemButtonTemplate.lua:461
 SetCurrency = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:8
 PostOnShow = <function> defined @FrameXML/ItemButtonTemplate.lua:414
 GetItemContextOverlayMode = <function> defined @FrameXML/ItemButtonTemplate.lua:471
 SetItemSource = <function> defined @FrameXML/ItemButtonTemplate.lua:528
 IsModifyingRequired = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:51
 ColorOverlay = Texture {
 }
 UpdateCursor = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:65
 GetCurrencyID = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:20
 SetBagID = <function> defined @FrameXML/ItemButtonTemplate.lua:639
 UpdateItemContextOverlay = <function> defined @FrameXML/ItemButtonTemplate.lua:488
 SetCropOverlayShown = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:43
 Count = FontString {
 }
 SetItemButtonAnchorPoint = <function> defined @FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = ProfessionsFrameSearchOverlay {
 }
 NormalTexture = ProfessionsFrameNormalTexture {
 }
 IconOverlay2 = Texture {
 }
 OnUpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:651
 OnItemContextChanged = <function> defined @FrameXML/ItemButtonTemplate.lua:410
 isModifyingRequired = false
 SetModifyingRequired = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:47
 SetItemButtonScale = <function> defined @FrameXML/ItemButtonTemplate.lua:623
 isCraftedItem = false
 noProfessionQualityOverlay = false
 isProfessionItem = false
 HighlightTexture = Texture {
 }
 itemContextMatchResult = 3
 InputOverlay = Frame {
 }
 AddIcon = Texture {
 }
 UpdateOverlay = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlotBase.lua:55
 QualityOverlay = Texture {
 }
 GetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:610
 SetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:532
 GetSlotAndBagID = <function> defined @FrameXML/ItemButtonTemplate.lua:647
 ItemContextOverlay = Texture {
 }
 Icon = Texture {
 }
 SetItemButtonTextureVertexColor = <function> defined @FrameXML/ItemButtonTemplate.lua:670
 GetItemID = <function> defined @FrameXML/ItemButtonTemplate.lua:591
 GetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:627
 RegisterBagButtonUpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:657
 SetItemButtonQuality = <function> defined @FrameXML/ItemButtonTemplate.lua:662
 PushedTexture = Texture {
 }
 SetLocked = <function> defined @Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeReagentSlot`

**Comment by jncl** [comment]
fixed by beta10.50199.1
