### ISSUE TITLE
[BUG]: Delve power selection frame  error

### ISSUE THREAD

**Issue by reiyooki** [jncl/Skinner#144]
**WoW Version**
Retail 11.0.2.56311

**AddOn skin name**
Retail Delve power choice frame

**Describe the bug**
Just an error when the frame appears.
Gist with error: https://gist.github.com/reiyooki/088ea8bae71cdc3e84ff2cd7c87d5f0a

**Comment by jncl** [comment]
Closed [#144](https://github.com/jncl/Skinner/issues/144) as completed via [15b2242](https://github.com/jncl/Skinner/commit/15b2242a8e660e96aaba6b5f1467f04fbc2d9464)
