### ISSUE TITLE
[BUG]: Log-in error

### ISSUE THREAD

**Issue by Aexxl** [jncl/Skinner#147]
**WoW Version**
_Retail_

**Describe the bug**
New error on log-in:

```
1x AceLocale-3.0-6: Skinner: Missing entry for 'Toggle the border of'
[string "@Skinner/Modules/UIButtons.lua"]:1284: in function `?'
[string "@Skinner/Core/Options.lua"]:1357: in function <Skinner/Core/Options.lua:93>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:359: in function <Skinner/Core/UtilFuncs.lua:352>
[string "=(tail call)"]: ?
[string "@Skinner/Core/Skinner.lua"]:72: in function <Skinner/Core/Skinner.lua:25>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

**Comment by MetalHeadSeven** [comment]
Same for me.

**Comment by Kilrahs** [comment]
Same here.

**Comment by AngelosNaoumis** [comment]
Dev did a mistake with locales he forgot "of" :D

For now open
Interface\AddOns\Skinner\Modules\UIButtons.lua
change line 1284
from
desc = _G.strjoin(" ", aObj.L["Toggle the border of"], aObj.L["the"], aObj.L["Frame Control Buttons"], aObj.L["(reload required)"]),
to
desc = _G.strjoin(" ", aObj.L["Toggle the border"], aObj.L["the"], aObj.L["Frame Control Buttons"], aObj.L["(reload required)"]),

**Comment by MetalHeadSeven** [comment]
> Dev did a mistake with locales he forgot "of" :D
> 
> For now open Interface\AddOns\Skinner\Modules\UIButtons.lua change line 1284 from desc = _G.strjoin(" ", aObj.L["Toggle the border of"], aObj.L["the"], aObj.L["Frame Control Buttons"], aObj.L["(reload required)"]), to desc = _G.strjoin(" ", aObj.L["Toggle the Border"], aObj.L["the"], aObj.L["Frame Control Buttons"], aObj.L["(reload required)"]),

That just creates a new error.
1x AceLocale-3.0-6: Skinner: Missing entry for 'Toggle the border'
[string "@Skinner/Modules/UIButtons.lua"]:1284: in function `?'
[string "@Skinner/Core/Options.lua"]:1357: in function <Skinner/Core/Options.lua:93>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:359: in function <Skinner/Core/UtilFuncs.lua:352>
[string "=(tail call)"]: ?
[string "@Skinner/Core/Skinner.lua"]:72: in function <Skinner/Core/Skinner.lua:25>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 fontX = fontX {
 }
 uarrow = "↑"
 modules = <table> {
 }
 fontSBX = fontSBX {
 }
 fontP = fontP {
 }
 darrow = "↓"
 defaultModuleState = true
 larrow = "←"
 fontDP = fontDP {
 }
 hooks = <table> {
 }
 fontS = fontS {
 }
 fontSB = fontSB {
 }
 enabledState = true
 searrow = "↘"
 fontBX = fontBX {
 }
 nearrow = "↗"
 defaultModuleLibraries = <table> {
 }
 nwarrow = "↖"
 orderedModules = <table> {
 }
 gearcog = "⛯"
 swarrow = "↙"
 rarrow = "→"
 mult = "×"
 name = "Skinner_UIButtons"
 fontDS = fontDS {
 }
 minus = "-"
 fontDX = fontDX {
 }
 plus = "+"
 moduleName = "UIButtons"
}
(*temporary) = <table> {
 type = "group"
 name = "Button Settings"
 order = 1
}
(*temporary) = <table> {
 ButtonBorders = <table> {
 }
 UIButtons = <table> {
 }
 CheckButtons = <table> {
 }
}
(*temporary) = <table> {
 type = "toggle"
 name = "Frame Control Buttons Border"
 order = 4
 width = "full"
}
(*temporary) = " "
(*temporary) = <table> {
 BF Toggle Border = "BF Toggle Border"
 Soulbinds Frame = "Soulbinds Frame"
 Set Border Width = "Set Border Width"
 Change the MF4 Frame Level = "Change the MF4 Frame Level"
 Macros UI = "Macros UI"
 Role Poll Popup = "Role Poll Popup"
 Islands Party Pose UI = "Islands Party Pose UI"
 Toggle the Rotation of the Gradient = "Toggle the Rotation of the Gradient"
 Professions Book Frame = ""
 Item Interaction UI = "Item Interaction UI"
 Unit Frames = "Unit Frames"
 Minimap icon = "Minimap icon"
 Disabled Text Colour = "Disabled Text Colour"
 Chat Config Frame = "Chat Config Frame"
 TF Alpha = "TF Alpha"
 Change the MF4 Frame Strata = "Change the MF4 Frame Strata"
 Spell Flyout = "Spell Flyout"
 AutoPopUps Skin = "AutoPopUps Skin"
 of the LFG Popup = "of the LFG Popup"
 Set Viewport Texture Filename = "Set Viewport Texture Filename"
 Class Talent UI = ""
 Adventure Map = "Adventure Map"
 Loot History Frame = "Loot History Frame"
 Change Opacity value of the Unit Frames' Background = "Change Opacity value of the Unit Frames' Background"
 Token UI = ""
 MF Toggle Border = "MF Toggle Border"
 Backdrop = "Backdrop"
 Gossip Frame = "Gossip Frame"
 Class Trial Frames = "Class Trial Frames"
 Middle Frame6 = "Middle Frame6"
 Alternate Power Bars = "Alternate Power Bars"
 Disable all the UI Frames from being skinned = "Disable all the UI Frames from being skinned"
 Scroll Of Resurrection = "Scroll Of Resurrection"
 Hide Border on Left and Top = "Hide Border on Left and Top"
 Stack Split Frame = "Stack Split Frame"
 Fade Height value = "Fade Height value"
 View Port = "View Port"
 Group Finder Frame = "Group Finder Frame"
 Middle Frame7 = "Middle Frame7"
 Boss Banner Toast = "Boss Banner Toast"
 Event Trace = "Event Trace"
 Set the Tooltips Border colour (Default, Custom) = "Set the Tooltips Border colour (Default, Custom)"
 Tooltip Border Colour = ""
 Set Gradient Maximum Colour = ""
 Disable all Addon/Library Skins = "Disable all Addon/Library Skins"
 Toggle the Global Fade Height = "Toggle the Global Fade Height"
 MiddleFrame6 Show = "MiddleFrame6 Show"
 BF Alpha = "BF Alpha"
 Trait UI = ""
 Set Border Texture Filename = "Set Border Texture Filename"
 Enable the Gradient Effect for the Skinner Frames = "Enable the Gradient Effect for the Skinner Frames"
 Middle Frame2 = "Middle Frame2"
 Change the ViewPort settings = "Change the ViewPort settings"
 Guild UI = "Guild UI"
 Tooltip = "Tooltip"
 BottomFrame Show = "BottomFrame Show"
 ObjectiveTracker Frame = "ObjectiveTracker Frame"
 Enable the Gradient Effect for the NPC Frames = "Enable the Gradient Effect for the NPC Frames"
 Obliterum UI = "Obliterum UI"
 Arena = "Arena"
 Textured Tab = "Textured Tab"
 New Player Experience Guide Frame = "New Player Experience Guide Frame"
 BattleNet Frames = "BattleNet Frames"
 MF9 Frame Level = "MF9 Frame Level"
 Initial Delay = "Initial Delay"
 Looking for Guild UI = ""
 Runes UI = ""
 Change the MF5 Frame Level = "Change the MF5 Frame Level"
 Report Frame = "Report Frame"
 Battlefield Frame = "Battlefield Frame"
 Skinner = "Skinner"
 Set the = "Set the"
 Change the MiddleFrame(s) settings = "Change

**Comment by AngelosNaoumis** [comment]
I did a bad copy paste, take the last edit
Toggle the border
instead of
Toggle the Border

**Comment by MetalHeadSeven** [comment]
Thanks that worked,
