### ISSUE TITLE
add !KalielsTracker

### ISSUE THREAD

**Issue by Axejess** [jncl/Skinner#152]
**WoW Version**
Which version(s) of WoW this AddOn is for: ( Retail / Wrath Classic / Classic Era / All ) 

**AddOn Name**
Name of the AddOn for which a skin is requested
!KalielsTracker
so that we can disable skinner for this one and dont get the errors bellow

32x AceLocale-3.0-6: Skinner: Missing entry for 'Toggle the border of'
[string "@Skinner/Modules/UIButtons.lua"]:1284: in function `?'
[string "@Skinner/Core/Options.lua"]:1357: in function <Skinner/Core/Options.lua:93>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:359: in function <Skinner/Core/UtilFuncs.lua:352>
[string "=(tail call)"]: ?
[string "@Skinner/Core/Skinner.lua"]:72: in function <Skinner/Core/Skinner.lua:25>
[string "=[C]"]: ?
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by jncl** [comment]
Do you still want this AddOn skinned as the missing localisation entry bug has now been resolved?

**Comment by Axejess** [comment]
Hey nah I just wanted the error gone. I haven't seen it poppup up today again so thank you ill close this
