### ISSUE TITLE
[BUG]: Clicking on quest item in delve

### ISSUE THREAD

**Issue by Acivien** [jncl/Skinner#161]
**WoW Version**
Retail

**AddOn skin name**
It's the WoW UI

**Describe the bug**
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Skinner' tried to call the protected function 'CastSpellByID()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpellByID'
[string "@Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.lua"]:1090: in function <...jectiveTracker/Blizzard_ScenarioObjectiveTracker.lua:1089>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by jncl** [comment]
Hi,
    This is caused by the Objective Tracker skin. You can either reload the UI which should allow the button to be pressed without an error, or disable the skinning of the Objective Tracker.
