### ISSUE TITLE
[BUG]: broken after new update

### ISSUE THREAD

**Issue by liononabicycle** [jncl/Skinner#170]
**WoW Version**
Retail

**AddOn skin name**
Skinner

I don't have a bug output for you because I don't get any errors but everything breaks with the new update. I had to roll back to the previous version. The new version is very inconsistent. The options to change the backdrop and background colors are gone. Some elements are skinned while others are not.

**Comment by Kilrahs** [comment]
Getting multiple errors.

Not sure if it is connected to the OPs problem or not.

3x Skinner/Core/NewSkinFuncs.lua:524: attempt to call method 'addButtonBorder' (a nil value)
[string "@Skinner/Core/NewSkinFuncs.lua"]:554: in function `?'
[string "@Skinner/Core/NewSkinFuncs.lua"]:288: in function `skinObject'
[string "@Skinner/AddonSkins/HandyNotes.lua"]:15: in function <Skinner/AddonSkins/HandyNotes.lua:5>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:358: in function <Skinner/Core/UtilFuncs.lua:351>
[string "=(tail call)"]: ?
[string "@Skinner/Core/AddonFrames.lua"]:103: in function `AddonFrames'
[string "@Skinner/Core/Skinner.lua"]:362: in function <Skinner/Core/Skinner.lua:362>


5x Skinner/Core/NewSkinFuncs.lua:703: attempt to call method 'skinCloseButton' (a nil value)
[string "@Skinner/Core/NewSkinFuncs.lua"]:753: in function `?'
[string "@Skinner/Core/NewSkinFuncs.lua"]:288: in function `skinObject'
[string "@Skinner/RetailSupport/UIFrames_Retail.lua"]:2757: in function <...aceSkinner/RetailSupport/UIFrames_Retail.lua:2563>
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:358: in function <Skinner/Core/UtilFuncs.lua:351>
[string "=(tail call)"]: ?
[string "@Skinner/Core/AddonFrames.lua"]:128: in function `BlizzardFrames'
[string "@Skinner/Core/Skinner.lua"]:360: in function <Skinner/Core/Skinner.lua:360>



3x Skinner/Core/UIFrames.lua:2691: attempt to index field 'modUIBtns' (a nil value)
[string "@Skinner/Core/UIFrames.lua"]:2691: in function <Skinner/Core/UIFrames.lua:2666>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `NavBar_AddButton'
[string "@Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua"]:525: in function `Refresh'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:356: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:353>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:880: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:866>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:511: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>



3x Skinner/Core/NewSkinFuncs.lua:472: attempt to call method 'addButtonBorder' (a nil value)
[string "@Skinner/Core/NewSkinFuncs.lua"]:472: in function <Skinner/Core/NewSkinFuncs.lua:429>
[string "@Skinner/Core/NewSkinFuncs.lua"]:476: in function `?'
[string "@Skinner/Core/NewSkinFuncs.lua"]:288: in function `skinObject'
[string "@Skinner/Core/UIFrames.lua"]:3214: in function <Skinner/Core/UIFrames.lua:3206>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_StaticPopup/Mainline/StaticPopup.lua"]:714: in function `StaticPopup_Show'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:1524: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:1290>


4x ...aceSkinner/RetailSupport/UIFrames_Retail.lua:3857: attempt to index field 'modUIBtns' (a nil value)
[string "@Skinner/RetailSupport/UIFrames_Retail.lua"]:3857: in function <...aceSkinner/RetailSupport/UIFrames_Retail.lua:3827>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:880: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:866>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:511: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>
