### ISSUE TITLE
[BUG]: ADDON_ACTION_FORBIDDEN

### ISSUE THREAD

**Issue by Aexxl** [jncl/Skinner#177]
**WoW Version**
_Retail_

**Describe the bug**
Trying to use the M+ Portals (the dropdown menu that expands to the portals)

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Skinner' tried to call the protected function 'CastSpellByID()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpellByID'
[string "@Blizzard_ActionBar/Mainline/SpellFlyout.lua"]:42: in function `SpellFlyoutButton_OnClick'
[string "*SpellFlyout.xml:37_OnClick"]:1: in function <[string "*SpellFlyout.xml:37_OnClick"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}
```

**Comment by jncl** [comment]
Hi,

You can try Reloading the UI to see if that fixes it, otherwise you will have to toggle the skin of the Spell Flyout option which can be found in the UI Frames options.

**Comment by Aexxl** [comment]
Same error and unable to use the portal after a reload or disabling the Spell Flyout option

**Comment by jncl** [comment]
Thanks for the feedback, I’ve never used the portal so will look into what is causing the issue in more detail.

**Comment by Aexxl** [comment]
To be a bit more precise: The dropdown (or Spell Flyout I guess) for the portals works fine (you click the icon and the portal options open), but if you want to use a portal / spell in the dropdown menu you get blocked by the above error message and with the usual forbidden action stuff from Blizzard (with the options to ignore the error or to disable the corresponding addon). Maybe that helps a little more than the initial description.
Keep up the great work!

**Comment by Aexxl** [comment]
There seems to be more problems with the ACTION_FORBIDDEN. If you try to use for example the guild bank out of the spell book there pops up another error and blocks you from using the spell

```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'Skinner' tried to call the protected function 'CastSpellBookItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpellBookItem'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:591: in function `OnIconClick'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:728: in function <...rd_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:724>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}
```

**Comment by Aexxl** [comment]
Another one. Got this in combat, but cannot reproduce.

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Skinner' tried to call the protected function 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:229: in function `AddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:163: in function `CheckAddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:174: in function `RefreshAllData'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:595: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:594>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:598: in function `OnMapChanged'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:303: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:314: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:312>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:880: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:866>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:511: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

**Comment by jncl** [comment]
Hi,
  These errors seem to be caused by the skinning of Buttons/Button Borders, can you try disabling them.

    If that doesn't fix the issue then I think they must be caused by skinning the parent frames, you can try disabling those and see if it fixes the issue.

**Comment by Aexxl** [comment]
**Spell book / talent frame:**

> 1x [ADDON_ACTION_FORBIDDEN] AddOn 'Skinner' tried to call the protected function 'CastSpellByID()'.

> 2x [ADDON_ACTION_FORBIDDEN] AddOn 'Skinner' tried to call the protected function 'CastSpellBookItem()'.

Disabling the skins of buttons / button borders does not fix the issue. 
With parent frames i guess you mean the spell book / talent frame. Disabling this skin "fixes" the issue

**The latest reported error**

> 1x [ADDON_ACTION_BLOCKED] AddOn 'Skinner' tried to call the protected function 'Button:SetPassThroughButtons()'.

I dont know. Could not reproduce until now. But If I remember correctly, this one occured during world questing, when you can use quest items via the quest log (the small buttons next to log entries). So they are probably two seperate issues?
