### ISSUE TITLE
add easier custom textures

### ISSUE THREAD

**Issue by liononabicycle** [jncl/Skinner#178]
**WoW Version**
Which version(s) of WoW this AddOn is for: Retail

I love this addon but the textures are limited. I read the instructions on how to add a texture and while I’m usually pretty good at figuring this kind of thing out, I couldn’t get it to work.

Is there a possibility of adding the ability to add more custom textures for backgrounds, borders, or buttons? An easier way to add those would be phenomenal. A way to add pixel borders without using a texture (which doesn’t always scale nicely) would be great, too.

I wasn’t sure where else to put this. Thanks again for your work.

**Comment by jncl** [comment]
Hi,
    You can add additional textures by using the SharedMedia & LibSharedMedia-3.0 AddOns.
    AFAIAA there isn't a way to add pixel borders, only textures can be added.
