### ISSUE TITLE
[BUG]: Blizzard_TokenUI collapsed category error

### ISSUE THREAD

**Issue by reiyooki** [jncl/Skinner#183]
**WoW Version**
Retail Version: 11.0.5.57388
Skinner Version: beta11-56819.1

**AddOn skin name**
Blizzard_TokenUI

**Describe the bug**
Skinner throws an error when hovering over a collapsible category in the currency window (Blizzard_TokenUI)

Lua Error:
https://gist.github.com/reiyooki/f2e267c051665bee2925e5e900730eaa

**Comment by jncl** [comment]
Hi,
    I'm unable to replicate this issue. Are you using any other AddOn which enhances the Currency frame?

**Comment by reiyooki** [comment]
Not to my knowledge, just went and checked and I didn't see anything that should be messing with that frame other than Skinner (/fstack didn't show anything either.) 

I was able to get the error to occur again by clicking the +/- to collapse a major category (War Within, specifically) - This happens each time the UI is reloaded with the category expanded, then clicking the "-" to collapse it.


![dBOgfo3DzK](https://github.com/user-attachments/assets/772c60cb-b8f1-4d07-9633-ccfca9ace00d)

**Comment by jncl** [comment]
Still can't replicate this issue.

Does this still happen when Skinner isn't loaded?

All I can suggest is that you delete the WoW Retail Cache directory and see if that fixes it.

**Comment by reiyooki** [comment]
Clearing my cache didn't seem to help. Disabling skinning on the character frames does prevent the error from occuring, but that's not really an ideal solution. It doesn't seem to actually break anything, but getting the error is a little annoying.

Trying to see if I can spot the issue in PlayerFrames.lua, but I don't see what the problem is there myself. It seems to point to this function though.
https://github.com/jncl/Skinner/blob/13b188ffbde3a43e2fb38a7676d49797645c11ce/Core/PlayerFrames.lua#L970
