### ISSUE TITLE
[BUG]:  ListScrollFrame nil reference for communities frame

### ISSUE THREAD

**Issue by HereticalHermit** [jncl/Skinner#22]
**WoW Version**
Retail
**AddOn skin name**
Skinner

**Describe the bug**

Recreate: 
1. Ensure 'Communities UI' frame is checked in Player Frames config
2. Open communities window with "J"

Error:
 Skinner/Core/PlayerFrames.lua:113: attempt to index field 'ListScrollFrame' (a nil value)
 Skinner/Core/PlayerFrames.lua:147: attempt to index field 'ListScrollFrame' (a nil value)
[string "@Skinner/Core/PlayerFrames.lua"]:113: in function <Skinner/Core/PlayerFrames.lua:83>
[string "@Skinner/Core/PlayerFrames.lua"]:147: in function <Skinner/Core/PlayerFrames.lua:120>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'

**Comment by Galthariel** [comment]
I have a similar error but happens when I open the Craft UI
