### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Nylrith** [jncl/Skinner#24]
**WoW Version**
RETAIL

**AddOn skin name**
LFG BUTTON AKA "EYE"

**Describe the bug**
When ever mousing over the LFG "eye", this error occurs and does not stop producing error messages until I
a) leave the LFG Tool or
b) do a relog.

I can open the LFG Interface with "i" and it gives no error. It simply seems to correlate with the said UI element.

1915x ...aceSkinner/RetailSupport/UIFrames_Retail.lua:3659: attempt to index field 'Texture' (a nil value)
[string "@Skinner/RetailSupport/UIFrames_Retail.lua"]:3659: in function `clrEntry'
[string "@Skinner/RetailSupport/UIFrames_Retail.lua"]:3667: in function <...aceSkinner/RetailSupport/UIFrames_Retail.lua:3646>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/QueueStatusFrame.lua"]:190: in function <FrameXML/QueueStatusFrame.lua:189>

Locals:
frame = QueueStatusFrame {
 0 = <userdata>
 layoutType = "TooltipDefaultLayout"
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:290
 TinyHookScript = <function> defined @TinyTooltip-Reforged/Core.lua:483
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:294
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/QueueStatusFrame.lua:397
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:302
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:271
 OnEvent = <function> defined @FrameXML/QueueStatusFrame.lua:432
 sf = Frame {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:298
 GetEntry = <function> defined @FrameXML/QueueStatusFrame.lua:443
 style = Frame {
 }
 statusEntriesPool = <table> {
 }
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:286
 Update = <function> defined =[C]:-1
 UpdatePosition = <function> defined @FrameXML/QueueStatusFrame.lua:665
}
r = 0.619608
g = 0.498039
b = 0.290196
_ = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = true
}
(for control) = Frame {
 0 = <userdata>
 DamagersFound = Frame {
 }
 AverageWait = FontString {
 }
 SubTitle = FontString {
 }
 Status = FontString {
 }
 orderIndex = 1
 RoleIcon2 = Texture {
 }
 RoleIcon3 = Texture {
 }
 TanksFound = Frame {
 }
 RoleIcon1 = Texture {
 }
 TimeInQueue = FontString {
 }
 Title = FontString {
 }
 queuedTime = 3066.521000
 HealersFound = Frame {
 }
 EntrySeparator = Texture {
 }
 AssignedSpec = Frame {
 }
 ExtraText = FontString {
 }
}
sEntry = Frame {
 0 = <userdata>
 DamagersFound = Frame {
 }
 AverageWait = FontString {
 }
 SubTitle = FontString {
 }
 Status = FontString {
 }
 orderIndex = 1
 RoleIcon2 = Texture {
 }
 RoleIcon3 = Texture {
 }
 TanksFound = Frame {
 }
 RoleIcon1 = Texture {
 }
 TimeInQueue = FontString {
 }
 Title = FontString {
 }
 queuedTime = 3066.521000
 HealersFound = Frame {
 }
 EntrySeparator = Texture {
 }
 AssignedSpec = Frame {
 }
 ExtraText = FontString {
 }
}
roleBtn = Frame {
 RoleIcon = Texture {
 }
 Count = QueueStatusFrameCount {
 }
 0 = <userdata>
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "Healers"
 2 = "Tanks"
 3 = "Damagers"
}
(for control) = 1
_ = 1
type = "Healers"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Texture' (a nil value)"
self = <table> {
 add2Table = <function> defined @Skinner/Core/SharedFuncs.lua:99
 makeIconSquare = <function> defined @Skinner/Core/UtilFuncs.lua:933
 blizzLoDFrames = <table> {
 }
 checkShown = <function> defined @Skinner/Core/UtilFuncs.lua:454
 modules = <table> {
 }
 blizzFrames = <table> {
 }
 changeTandC = <function> defined @Skinner/Core/UtilFuncs.lua:267
 Debug3 = <function> defined @FrameXML/UIParent.lua:5254
 isButton = <function> defined @Skinner/Modules/UIButtons.lua:250
 bColour = <table> {
 }
 rarrow = "→"
 larrow = "←"
 setupOptions = <function> defined @Skinner/Core/SharedFuncs.lua:108
 ADDON_LOADED = <function> defined @Skinner/Core/AddonFrames.lua:182
 mmButs = <table> {
 }
 getInt = <function> defined @Skinner/Core/UtilFuncs.lua:676
 addButtonBorder = <function> defined @FrameXML/UIParent.lua:5254
 skinTooltip = <function> defined @Skinner/Core/MainFuncs.lua:1190
 db = <table> {
 }
 clrButtonFromBorder = <function> defined @FrameXML/UIParent.lua:5254
 SetupDefaults = <function> defined @Skinner/Core/Options.lua:6
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:273
 isTT = true
 Backdrop = <tabl

**Comment by jncl** [comment]
Closed by +d85ef88e
