### ISSUE TITLE
[BUG]: ToT don't work

### ISSUE THREAD

**Issue by Leseulunik** [jncl/Skinner#25]
**WoW Version**
Retail

**Describe the bug**
ToT don't work

2x [ADDON_ACTION_BLOCKED] L'AddOn 'Skinner' a tenté d'appeler la fonction protégée 'TargetFrameToT:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Hide'
[string "@FrameXML/TargetFrame.lua"]:1166: in function <FrameXML/TargetFrame.lua:1149>
[string "=[C]"]: in function `Update'
[string "@FrameXML/TargetFrame.lua"]:129: in function <FrameXML/TargetFrame.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@FrameXML/TargetFrame.lua"]:162: in function `OnEvent'
[string "@FrameXML/UnitFrame.lua"]:1070: in function <FrameXML/UnitFrame.lua:1068>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

**Comment by jncl** [comment]
Skinner no longer skins UnitFrames in Retail so I'm not sure why you are seeing this error. I cannot replicate it so therefore am unable to make any changes.
Is it still occurring?, if so can you give me some idea of how to replicate it so I can try to apply a fix for it if I can.
Thanks

**Comment by jncl** [comment]
Closed as there has been no additional response
