### ISSUE TITLE
[BUG]: not working with 1.14.4 wow classic client

### ISSUE THREAD

**Issue by ipmml** [jncl/Skinner#26]
**WoW Version**
Which version of WoW this bug occurs in:  ( Retail / Wrath Classic / Classic Era / All ) 

**AddOn skin name**
Name of the AddOn skin producing this bug, if known

**Describe the bug**
Please include the Output from the bug reporting tool

**Comment by jncl** [comment]
Closed by +25e2967a

**Comment by jncl** [comment]
Closed by +25e2967a
