### ISSUE TITLE
[BUG]: No access to most Skinner Options.

### ISSUE THREAD

**Issue by MetalHeadSeven** [jncl/Skinner#27]
Retail

I hadn't been using Skinner for a little while because issues with the Vehicle Override Bar when using Dominos.  But I like Skinner so much I decided to reinstall it.

I can't access any settings except the first tab.  There's not even a + button to expand Skinner Options.  I also tried with only Skinner enabled same error same missing + button.
![Missing Options](https://github.com/jncl/Skinner/assets/34187628/8e27f46d-90db-4a39-9ba8-f4a69a28bc0c)

3x ...aceSkinner/RetailSupport/UIFrames_Retail.lua:4094: Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object
[string "@Postal/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:143: in function <...rfacePostal/Libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Postal/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:410: in function `SecureHookScript'
[string "@Skinner/RetailSupport/UIFrames_Retail.lua"]:4094: in function <...aceSkinner/RetailSupport/UIFrames_Retail.lua:4023>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `xpcall'
[string "@Skinner/Core/UtilFuncs.lua"]:310: in function <Skinner/Core/UtilFuncs.lua:304>
[string "=(tail call)"]: ?
[string "@Skinner/Core/AddonFrames.lua"]:140: in function `BlizzardFrames'
[string "@Skinner/Core/Skinner.lua"]:473: in function <Skinner/Core/Skinner.lua:473>

Locals:
self = <table> {
 add2Table = <function> defined @Skinner/Core/SharedFuncs.lua:96
 makeIconSquare = <function> defined @Skinner/Core/UtilFuncs.lua:920
 blizzLoDFrames = <table> {
 }
 checkShown = <function> defined @Skinner/Core/UtilFuncs.lua:452
 modules = <table> {
 }
 blizzFrames = <table> {
 }
 changeTandC = <function> defined @Skinner/Core/UtilFuncs.lua:263
 Debug3 = <function> defined @FrameXML/UIParent.lua:5254
 isButton = <function> defined @FrameXML/UIParent.lua:5254
 bColour = <table> {
 }
 rarrow = <function> defined @FrameXML/UIParent.lua:5254
 larrow = <function> defined @FrameXML/UIParent.lua:5254
 setupOptions = <function> defined @Skinner/Core/SharedFuncs.lua:105
 ADDON_LOADED = <function> defined @Skinner/Core/AddonFrames.lua:182
 mmButs = <table> {
 }
 getInt = <function> defined @Skinner/Core/UtilFuncs.lua:663
 addButtonBorder = <function> defined @FrameXML/UIParent.lua:5254
 skinTooltip = <function> defined @Skinner/Core/MainFuncs.lua:1191
 db = <table> {
 }
 clrButtonFromBorder = <function> defined @FrameXML/UIParent.lua:5254
 SetupDefaults = <function> defined @Skinner/Core/Options.lua:6
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Postal/Libs/AceHook-3.0/AceHook-3.0.lua:273
 isTT = false
 Backdrop = <table> {
 }
 bdTexName = "Blizzard ChatFrame Background"
 setActiveTab = <function> defined @Skinner/Core/UtilFuncs.lua:1228
 isClscERAPTR = false
 setupFramesOptions = <function> defined @Skinner/Core/UtilFuncs.lua:1296
 AddonFrames = <function> defined @Skinner/Core/AddonFrames.lua:111
 hasTextInName = <function> defined @Skinner/Core/UtilFuncs.lua:715
 iofDD = <table> {
 }
 bdbTexName = "Blizzard Tooltip"
 UnregisterAllEvents = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 skinGlowBox = <function> defined @Skinner/Core/MainFuncs.lua:727
 isRtl = true
 nearrow = <function> defined @FrameXML/UIParent.lua:5254
 hook = <function> defined @Skinner/Core/UtilFuncs.lua:767
 ttHook = <table> {
 }
 isClsc = false
 GetName = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "Skinner"
 Disable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 round2 = <function> defined @Skinner/Core/UtilFuncs.lua:1178
 ebRgns = <table> {
 }
 findFrame2 = <function> defined @Skinner/Core/UtilFuncs.lua:550
 Unhook = <function> defined @Postal/Libs/AceHook-3.0/AceHook-3.0.lua:417
 addSkinFrame = <function> defined @Skinner/Core/MainFuncs.lua:333
 skinStatusBar = <function> defined @Skinner/Core/MainFuncs.lua:1028
 isClscERA = false
 clrBtnBdr = <function> defined @FrameXML/UIParent.lua:5254
 L = <table> {
 }
 pbtt = <table> {
 }
 Debug = <function> defined @FrameXML/UIParent.lua:5254
 BTr = 0.600000
 checkLoadable = <function> defined @Skinner/Core/UtilFuncs.lua:438
 skinTabs = <function> defined @Skinner/Core/MainFuncs.lua:1154
 SetupOptions = <function> defined @Skinner/Core/Options.lua:93
 HTr = 0.800000
 modUIBtns = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 iofSkinnedPanels = <table> {
 }
 EnableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 DBIcon = <table> {
 }
 RawHookScript = <function> defined @Postal/Libs/AceHook-3.0/AceHook-3.0.lua:394
 getLastChild = <function> defined @I

**Comment by jncl** [comment]
Updated SharedFuncs to display options, fixes #27
