### ISSUE TITLE
StanceBarSetShow Lua Error

### ISSUE THREAD

**Issue by Galthariel** [jncl/Skinner#3]
**WoW Version**
Retail

**AddOn skin name**
Unknown

**Describe the bug**
1x [ADDON_ACTION_BLOCKED] AddOn 'Skinner' tried to call the protected function 'StanceBar:SetShownBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetShownBase'
[string "@FrameXML/ActionBar.lua"]:315: in function `UpdateVisibility'
[string "@FrameXML/ActionBar.lua"]:302: in function `ShowOverride'
[string "@FrameXML/ActionBar.lua"]:292: in function `SetShown'
[string "@FrameXML/StanceBar.lua"]:33: in function `Update'
[string "@FrameXML/ActionBarController.lua"]:132: in function <FrameXML/ActionBarController.lua:130>
[string "=[C]"]: in function `ActionBarController_UpdateAll'
[string "@FrameXML/ActionBarController.lua"]:66: in function <FrameXML/ActionBarController.lua:55>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

I long time Error

**Comment by jncl** [comment]
Are you using an ActionBar AddOn?

If not I suggest you do so as I can't fix this issue because I don't know what's causing it.

**Comment by jncl** [comment]
Are you using an ActionBar AddOn?

If not I suggest you do so as I can't fix this issue because I don't know what's causing it.
