### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Acivien** [jncl/Skinner#37]
**WoW Version**
Retail

**AddOn skin name**
Unknown

**Describe the bug**
1x [ADDON_ACTION_BLOCKED] AddOn 'Skinner' tried to call the protected function 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:189: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:228: in function `AddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:142: in function `CheckAddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:153: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:102: in function `OnEvent'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:106: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:105>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:109: in function `OnEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:109: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:108>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by jncl** [comment]
Can't replicate this bug, it's probably related to the skinning of the WorldMap, AFAIAA there is nothing I can do about it.
