### ISSUE TITLE
MultiBarBottomLeftButton Lua Error

### ISSUE THREAD

**Issue by Galthariel** [jncl/Skinner#4]
**WoW Version**
Retail
**AddOn skin name**
Unknown

**Describe the bug**
1x [ADDON_ACTION_BLOCKED] AddOn 'Skinner' tried to call the protected function 'MultiBarBottomLeftButton3:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function SetAttribute' [string "@FrameXML/ActionButton.lua"]:335: in function UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:395: in function <FrameXML/ActionButton.lua:356>
[string "=[C]"]: in function Update' [string "@FrameXML/ActionButton.lua"]:347: in function <FrameXML/ActionButton.lua:342> [string "=[C]"]: in function UpdateAction'
[string "@FrameXML/ActionButton.lua"]:809: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:200: in function <FrameXML/ActionButton.lua:197>

Locals:
_ = Frame {
RegisterEvent = defined @!BugGrabber/BugGrabber.lua:487
0 =
UnregisterEvent = defined @!BugGrabber/BugGrabber.lua:487
SetScript = defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events =
{
ADDON_ACTION_BLOCKED = defined @!BugGrabber/BugGrabber.lua:553
ADDON_ACTION_FORBIDDEN = defined @!BugGrabber/BugGrabber.lua:553
PLAYER_LOGIN = defined @!BugGrabber/BugGrabber.lua:547
LUA_WARNING = defined @!BugGrabber/BugGrabber.lua:562
ADDON_LOADED = defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by jncl** [comment]
Are you using an ActionBar AddOn?

If not I suggest you do so as I can't fix this issue because I don't know what's causing it.
