### ISSUE TITLE
[BUG] [RETAIL]: View port appears to bugged.

### ISSUE THREAD

**Issue by TreizeEU** [jncl/Skinner#41]
**WoW Version**

Retail, since 10.2 release.

**Describe the bug**

View port seems to not work correctly for me? I've originally set the top VP by 55. When I set that number to 0, nothing happens. If I set it back to 55, it changes to what it should be set to. This effect sometimes happens during dungeons and raids (and outdoor world quest cinematics). When I reload UI, it'll go back to the state of 0 but with it set to 55.

Any ideas why this happens?

**Comment by silverwind** [comment]
Seeing this as well, apparently viewport is no longer applied on reloadui recently.
