### ISSUE TITLE
Edit box border

### ISSUE THREAD

**Issue by dntsy1** [jncl/Skinner#49]
I can't find a different way to reach you, so I gotta do it here.

I quite like your addon as a lightweight way to get a more minimalistic view, but I'm confused regarding some of the functionality:
![grafik](https://github.com/jncl/Skinner/assets/138626792/26ee80fa-dea0-443b-85c8-4c40e7881640)

Where can I change the border of edit boxes like these (or the search box etc.)? I absolutely can't find it, and it looks atrocious right now :D
I know I can change the *colour* of it in the default colours section, but where can I change the thickness? For some reason they turned out *absurdly* thick with this addon as you can see.

In any case though, ty for all the work :)

Edit: it appears that buttons also have such a gigantic border if you skin them

**Comment by dntsy1** [comment]
And where's the option to select a colour for buttons? And various objects in general?

A lot of things get skinned, but have no option to select a colour that I can see.

**Comment by jncl** [comment]
Hi,
    Sorry I've taken so long to reply to this.
    The border used for Edit Boxes, Buttons etc is the same one used for frames and can be changed by choosing a different texture for the Background Border setting, The Width and Inset values can also be changed there.
    To change the colour of the skinned objects use the various Colours settings.

    HTH
