### ISSUE TITLE
[BUG]: Error when loading into game addon does not load

### ISSUE THREAD

**Issue by Aenimma** [jncl/Skinner#6]
**WoW Version**
Which version of WoW this bug occurs in  (Retail, Wrath Classic, Classic Era) 

**AddOn skin name**
Name of the AddOn skin producing this bug, if known

**Describe the bug**
Date: 2023-06-14 12:05:51
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Skinner/Core/Options.lua line 104:
   attempt to index field 'Settings' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: xpcall()
   [string "@Interface/AddOns/Skinner/Core/UtilFuncs.lua"]:292:
      Interface/AddOns/Skinner/Core/UtilFuncs.lua:286
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Skinner/Core/Skinner.lua"]:89:
      Interface/AddOns/Skinner/Core/Skinner.lua:37
   [string "=[C]"]: ?
   [string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      .../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: InitializeAddon()
   [string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619:
      .../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.8.6
  Altoholic, v3.4.002
  AtlasLootClassic, vv3.1.2
  AtlasLootClassicData, vv3.1.2
  AtlasLootClassicDungeonsAndRaids, vv3.1.2
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.1.7
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  Coordinates, v2.4.1
  DataStore, v2023.05.04
  DataStoreAchievements, v2023.05.03
  DataStoreAgenda, v2023.05.18
  DataStoreAuctions, v3.4.001
  DataStoreCharacters, v2023.05.03
  DataStoreContainers, v3.4.001
  DataStoreCrafts, v3.4.001
  DataStoreCurrencies, v2023.05.18
  DataStoreInventory, v3.4.001
  DataStoreMails, v2023.05.04
  DataStoreQuests, v3.4.001
  DataStoreReputations, v3.4.001
  DataStoreSpells, v2023.05.03
  DataStoreTalents, v3.4.001
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  GatherMate2, v1.47-classic
  GuildRosterManager, v1.977
  LeatrixMaps, v3.0.135
  LeatrixPlus, v3.0.135
  Mapster, v1.10.8
  NovaSpellRankChecker, v1.2
  PallyPower, vv1.5.2-classic
  Pawn, v2.8.1
  Postal, vv3.9.7
  Prat30, v3.9.30
  Prat30Libraries, v
  Quartz, v3.7.5
  Questie, v8.5.1
  Skinner, vbeta10.49908.2
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=66b)

**Comment by jncl** [comment]
Fixed in beta10.50000.1
