### ISSUE TITLE
[BUG]:  Missing Skins

### ISSUE THREAD

**Issue by IrishMoxie** [jncl/Skinner#60]
Rematch unfortunately doesn't appear to be skinned even with the update. Various elements are still "default". PetBattleTeams also appears to be the same way. Opie also has a standalone options window that's unskinned.

![image](https://github.com/jncl/Skinner/assets/16712129/46e29bcd-e05d-451c-bffd-4a4889c75013)

![image](https://github.com/jncl/Skinner/assets/16712129/d3bee44a-5a19-4c47-b457-93dcec64d951)

**Comment by IrishMoxie** [comment]
Auctionator also appears to be exactly the same as before. Maybe because it was just updated? I'm not sure. I haven't received any errors yet. I've downloaded the latest file from Curseforge multiple times just to make sure, and tried a completely fresh install on retail.

**Comment by jncl** [comment]
Hi,
    The skin for Rematch is a work in progress. There are some areas I currently can't skin as they are composite textures but I am trying to find a way to skin them.
    PetBattle Teams AddOn hasn't been updated since 2018 on CurseForge and the version I have has errors and won't run, if you have a version that does run I'm happy to use it to make changes to the skin.
    Opie doesn't have a skin at all. I can make one if requested to do so.
    Auctionator's skin is AFAIAA fine , everything seems skinned to me, what exactly is the issue that you are experiencing?

**Comment by IrishMoxie** [comment]
Good to hear about Rematch!

PetBattleTeams has thankfully had a new fork that's been fairly regularly updated - and works - here: https://www.curseforge.com/wow/addons/petbattle-teams/files/all?page=1&pageSize=20

As for Auctionator, the selling tab still has an unskinned scrollbar and various elements for me. I'm not sure why if it's fine on your end; I can live with it.

**Comment by jncl** [comment]
Hi,
    I loaded the version of PetBattleTeams you pointed me too and the skin looks ok to me, are you getting any errors relating to its skin?
    As for Auctionator are there any errors reported for its skin? I don't have many other AddOns loaded and it seems ok to me.

**Comment by IrishMoxie** [comment]
No errors for PBT, it just doesn't look skinned to me. As you can see on the left side of the screenshot, everything is smooth and "skinned". The teams look unskinned in comparison.

Auctionator just has some minor elements that look like the default skin - scrollbar, some other little bits - but if it looks fine for you then it's nothing to add to your work over. 

I did forget to add that a skin for Opie would be great, I always thought it had been but I've been away for a few years so am probably misremembering.

![image](https://github.com/jncl/Skinner/assets/16712129/a3b6eb5b-81b5-4d97-a3fa-ae882fcc4008)

**Comment by jncl** [comment]
Hi,
  The image you posted shows the Rematch skin, to see the PetBattle Teams skin you need to untick the Rematch Checkbox on the PetJournal page.
  I am slowly working through the changes required for Rematch.
  I will skin Opie for you.

**Comment by IrishMoxie** [comment]
That's what I get for being gone a few years, I forgot the basics like the Rematch box which is right in front of my face. Thanks!
