### ISSUE TITLE
[BUG]: Icons not showing on character panel

### ISSUE THREAD

**Issue by Infitheta** [jncl/Skinner#62]
Retail
Which version of WoW this bug occurs in:  ( Retail / Wrath Classic / Classic Era / All ) 

Installing Skinner produced the bug, also using Masque 
Name of the AddOn skin producing this bug, if known

All the icons for my equipped items have disappeared on my character frame, please see attached image
![864f90e7a1b80ed224bc3f5a7605bb94](https://github.com/jncl/Skinner/assets/113709850/1a283de1-e6b4-45ff-ae90-acf9a7a14d0c)

**Comment by jncl** [comment]
Hi,
  Which AddOns are you using to add the Item Level and other info to the equipped items?, I will install them to see if they're causing the issue as I haven't had other reports of missing icons recently.

**Comment by Infitheta** [comment]
The only two I can think that might be doing anything to do it would be BetterCharacterPanel and DejaCharacterStats. I turned them both off and still experiencing the issue: 
![2005ed1567b5ab24831de0ced8ee669a](https://github.com/jncl/Skinner/assets/113709850/9e7d3112-82f3-4b9e-a251-95726cfc2143)

**Comment by jncl** [comment]
Hi,
  Can you disable all other AddOns apart from Skinner please and see if that makes a difference. 
  It looks like another AddOn skin is causing this issue, can you also confirm that the Modules --> Button Settings -- > Button Borders option is unticked please.

**Comment by Infitheta** [comment]
That worked - looks like it was one of my Masque packs that was causing the issue. Thanks man!

**Comment by jncl** [comment]
Hi,
  That's good news, closing this as it's a non-Skinner issue.
