### ISSUE TITLE
[BUG]: nil reference with new version of BetterBags

### ISSUE THREAD

**Issue by HereticalHermit** [jncl/Skinner#78]
**WoW Version**
Retail

**AddOn skin name**
BetterBags

**Describe the bug**
2x Skinner/AddonSkins/BetterBags.lua:51: attempt to index a nil value
[string "@Skinner/AddonSkins/BetterBags.lua"]:51: in function <Skinner/AddonSkins/BetterBags.lua:48>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `Show'
[string "@BetterBags/frames/bag.lua"]:124: in function `Show'
[string "@BetterBags/core/hooks.lua"]:48: in function `cb'
[string "@BetterBags/core/events.lua"]:50: in function <BetterBags/core/events.lua:45>
[string "=[C]"]: ?

**Comment by amey1956** [comment]
same type of error on cata, referencing a different line: 

`16x Skinner/AddonSkins/BetterBags.lua:53: attempt to index a nil value
[string "@Skinner/AddonSkins/BetterBags.lua"]:53: in function <Skinner/AddonSkins/BetterBags.lua:48>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `Show'
[string "@BetterBags/frames/bag.lua"]:124: in function `Show'
[string "@BetterBags/core/hooks.lua"]:48: in function `cb'
[string "@BetterBags/core/events.lua"]:50: in function <BetterBags/core/events.lua:45>
[string "=[C]"]: ?
[string "@AnnoyingPopupRemover/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ver/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AnnoyingPopupRemover/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:176: in function `SendMessage'
[string "@BetterBags/core/hooks.lua"]:91: in function `ToggleAllBags'
[string "@BetterBags/core/init.lua"]:87: in function `BetterBags_ToggleBags'
[string "BETTERBAGS_TOGGLEBAGS"]:1: in function <[string "BETTERBAGS_TOGGLEBAGS"]:1>

Locals:
this = BetterBagsBagBackpack {
 0 = <userdata>
 Owner = <table> {
 }
 sf = Frame {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = BetterBagsBagBackpack {
 0 = <userdata>
 Owner = <table> {
 }
 sf = Frame {
 }
}
(*temporary) = 18
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
aObj = <table> {
 add2Table = <function> defined @Skinner/Core/SharedFuncs.lua:132
 makeIconSquare = <function> defined @Skinner/Core/UtilFuncs.lua:955
 blizzLoDFrames = <table> {
 }
 checkShown = <function> defined @Skinner/Core/UtilFuncs.lua:458
 getChild = <function> defined @Skinner/Core/UtilFuncs.lua:607
 isAddOnLoadOnDemand = <function> defined @Skinner/Core/UtilFuncs.lua:847
 tbClr = <table> {
 }
 changeTandC = <function> defined @Skinner/Core/UtilFuncs.lua:263
 Debug3 = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 isButton = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 bColour = <table> {
 }
 rarrow = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 larrow = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 setupOptions = <function> defined @Skinner/Core/SharedFuncs.lua:141
 ADDON_LOADED = <function> defined @Skinner/Core/AddonFrames.lua:177
 mmButs = <table> {
 }
 getInt = <function> defined @Skinner/Core/UtilFuncs.lua:668
 addButtonBorder = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 skinTooltip = <function> defined @Skinner/Core/MainFuncs.lua:1183
 db = <table> {
 }
 clrButtonFromBorder = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 SetupDefaults = <function> defined @Skinner/Core/Options.lua:6
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 SetupClassic_NPCFramesOptions = <function> defined @Skinner/ClassicSupport/NPCFrames_Classic.lua:373
 isTT = false
 Backdrop = <table> {
 }
 bdTexName = "Blizzard ChatFrame Background"
 hookSocialToastFuncs = <function> defined @Skinner/Core/UtilFuncs.lua:795
 isClscERAPTR = false
 setupFramesOptions = <function> defined @Skinner/Core/UtilFuncs.lua:1331
 AddonFrames = <function> defined @Skinner/Core/AddonFrames.lua:107
 hasTextInName = <function> defined @Skinner/Core/UtilFuncs.lua:720
 iofDD = <table> {
 }
 bdbTexName = "Blizzard Tooltip"
 UnregisterAllEvents = <function> defined @AnnoyingPopupRemover/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 skinGlowBox = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 keepFontStrings = <function> defined @Skinner/Core/UtilFuncs.lua:892
 XLoot = <function> defined @Skinner/AddonSkins/XLoot.lua:5
 hook = <function> defined @Skinner/Core/UtilFuncs.lua:772
 ttDelay = 0.200000
 ttHook = <table> {
 }
 isClsc = true
 GetName = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "Skinner"
 Disable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 round2 = <function> defined @Skinner/Core/UtilFuncs.lua:1213
 ebRgns = <table> {
 }
 findFrame2 = <function> defined @Skinner/Core/UtilFuncs.lua:558
 Unhook = <function> defined @BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:417
 addSkinFrame = <function> defined @Skinner/Core/MainFuncs.lua:333
 skinStatusBar = <function> defined @Skinner/Core/MainFuncs.lua:1020
 isClscERA = false
 clrBtnBdr = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 L = <table> {
 }
 Debug = <function> defined @Blizzard_UIParent/Cata/UIParent.lua:3182
 BTr = 0.600000
 checkLoadable = <function> defined `
