### ISSUE TITLE
Same Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [jncl/Skinner#99]
Same error on Retail with latest version.

1x AceLocale-3.0-6: Skinner: Missing entry for 'Professions Book Frame'
[string "@Skinner/Core/UtilFuncs.lua"]:1362: in function `setupFramesOptions'
[string "@Skinner/RetailSupport/PlayerFrames_Retail.lua"]:2633: in function `SetupRetail_PlayerFramesOptions'
[string "@Skinner/Core/Skinner.lua"]:78: in function <Skinner/Core/Skinner.lua:26>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 blizzLoDFrames = <table> {
 }
 modules = <table> {
 }
 isClscBeta = false
 hooks = <table> {
 }
 isClscERAPTR = false
 isRtlPTR = false
 ttDelay = 0.200000
 isClsc = false
 isRtlPTRX = false
 name = "Skinner"
 LSM = <table> {
 }
 optCheck = <table> {
 }
 isClscERA = false
 L = <table> {
 }
 optionsFrames = <table> {
 }
 optTables = <table> {
 }
 uName = "Firehööf"
 db = <table> {
 }
 tFDIDs = <table> {
 }
 uCls = "DRUID"
 DBIcon = <table> {
 }
 baseName = "Skinner"
 isPatch = false
 ignoreQT = <table> {
 }
 aboutPanels = <table> {
 }
 ACD = <table> {
 }
 iofSkinnedPanels = <table> {
 }
 defaultModuleState = true
 addonsToSkin = <table> {
 }
 ACR = <table> {
 }
 enabledState = true
 libsToSkin = <table> {
 }
 skinTPLs = <table> {
 }
 lodAddons = <table> {
 }
 prdb = <table> {
 }
 blizzFrames = <table> {
 }
 isRtl = true
 isRtlBeta = false
 isClscPTR = false
 callbacks = <table> {
 }
 orderedModules = <table> {
 }
 otherAddons = <table> {
 }
 ItemPimper = true
 defaultModuleLibraries = <table> {
 }
}
optTab = <table> {
 Guild Control UI = true
 PVP UI = <table> {
 }
 Equipment Flyout = true
 Azerite Essence UI = true
 Guild Invite = <table> {
 }
 Artifact UI = true
 Azerite UI = true
 Professions = true
 Professions Book = <table> {
 }
 Character Customize = <table> {
 }
 Looking For Guild UI = <table> {
 }
 Currency Transfer = true
 Guild UI = true
 Player Spells = true
}
framesType = "Player"
opt = "ProfessionsBook"
oDesc = "Professions Book Frame"
(for state) = <table> {
 Guild Control UI = true
 PVP UI = <table> {
 }
 Equipment Flyout = true
 Azerite Essence UI = true
 Guild Invite = <table> {
 }
 Artifact UI = true
 Azerite UI = true
 Professions = true
 Professions Book = <table> {
 }
 Character Customize = <table> {
 }
 Looking For Guild UI = <table> {
 }
 Currency Transfer = true
 Guild UI = true
 Player Spells = true
}
(for control) = "Professions Book"
optName = "Professions Book"
optVals = <table> {
 suff = "Frame"
}
(*temporary) = <table> {
 Collections = <table> {
 }
 CastingBar = <table> {
 }
 Professions = <table> {
 }
 ContainerFrames = <table> {
 }
 ReadyCheck = <table> {
 }
 ArtifactUI = <table> {
 }
 head2 = <table> {
 }
 PVPUI = <table> {
 }
 GuildInvite = <table> {
 }
 FriendsFrame = <table> {
 }
 RolePollPopup = <table> {
 }
 head1 = <table> {
 }
 MirrorTimers = <table> {
 }
 EquipmentFlyout = <table> {
 }
 CharacterFrames = <table> {
 }
 ArchaeologyUI = <table> {
 }
 AchievementUI = <table> {
 }
 InspectUI = <table> {
 }
 DressUpFrame = <table> {
 }
 Buffs = <table> {
 }
 ItemSocketingUI = <table> {
 }
 EncounterJournal = <table> {
 }
 LootFrames = <table> {
 }
 GuildControlUI = <table> {
 }
 AzeriteEssenceUI = <table> {
 }
 CompactFrames = <table> {
 }
 DisableAllP = <table> {
 }
 RaidUI = <table> {
 }
 TradeFrame = <table> {
 }
 Communities = <table> {
 }
 AzeriteUI = <table> {
 }
}
(*temporary) = <table> {
 type = "toggle"
}
(*temporary) = <table> {
 BF Toggle Border = "BF Toggle Border"
 Soulbinds Frame = "Soulbinds Frame"
 Set Border Width = "Set Border Width"
 Change the MF4 Frame Level = "Change the MF4 Frame Level"
 Macros UI = "Macros UI"
 Role Poll Popup = "Role Poll Popup"
 Islands Party Pose UI = "Islands Party Pose UI"
 Toggle the Rotation of the Gradient = "Toggle the Rotation of the Gradient"
 Professions Book Frame = "Professions Book Frame"
 Item Interaction UI = "Item Interaction UI"
 Unit Frames = "Unit Frames"
 Minimap icon = "Minimap icon"
 MF8 Frame Level = "MF8 Frame Level"
 Chat Config Frame = "Chat Config Frame"
 TF Alpha = "TF Alpha"
 Change the MF4 Frame Strata = "Change the MF4 Frame Strata"
 Spell Flyout = "Spell Flyout"
 AutoPopUps Skin = "AutoPopUps Skin"
 of the LFG Popup = "of the LFG Popup"
 Set Viewport Texture Filename = "Set Viewport Texture Filename"
 Class Talent UI = ""
 Adventure Map = "Adventure Map"
 Loot History Frame = "Loot History Frame"
 Change Opacity value of the Unit Frames' Background = "Change Opacity value of the Unit Frames' Background"
 Token UI = "Token UI"
 MF Toggle Border = "MF Toggle Border"
 Backdrop = "Backdrop"
 Goss

**Comment by jncl** [comment]
Closed [#99](https://github.com/jncl/Skinner/issues/99) as completed via [e435282](https://github.com/jncl/Skinner/commit/e4352822ec4f6fbc5b03b26752e1d9f69d5f86e5)

**Comment by jncl** [comment]
Closed [#99](https://github.com/jncl/Skinner/issues/99) as completed via [e435282](https://github.com/jncl/Skinner/commit/e4352822ec4f6fbc5b03b26752e1d9f69d5f86e5)
